#!/bin/sh	
WLAN_DRIVER_INSMOD_DONE=
echo WLAN_DRIVER_INSMOD_DONE=$WLAN_DRIVER_INSMOD_DONE
while [ -z $WLAN_DRIVER_INSMOD_DONE ]
	do
		sleep 1
		WLAN_DRIVER_INSMOD_DONE=`/bin/cat /proc/modules | /bin/grep -e 'wl '`
		echo WLAN_DRIVER_INSMOD_DONE=$WLAN_DRIVER_INSMOD_DONE
	done
echo WLAN_DRIVER_INSMOD_DONE=$WLAN_DRIVER_INSMOD_DONE
